[build]
pre-build = ["apt-get update && apt-get install -y libdbus-1-dev"]

[target.x86_64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y musl-tools"]

[target.aarch64-unknown-linux-musl]
pre-build = ["apt-get update && apt-get install -y musl-tools"]
